//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetupSurvey.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MeetupSurvey.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CurrentSurveys {
            get {
                return ResourceManager.GetString("CurrentSurveys", resourceCulture);
            }
        }
        
        public static string ArchivedSurveys {
            get {
                return ResourceManager.GetString("ArchivedSurveys", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string PleaseFinish {
            get {
                return ResourceManager.GetString("PleaseFinish", resourceCulture);
            }
        }
        
        public static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        public static string SurveyName {
            get {
                return ResourceManager.GetString("SurveyName", resourceCulture);
            }
        }
        
        public static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        public static string Organizers {
            get {
                return ResourceManager.GetString("Organizers", resourceCulture);
            }
        }
        
        public static string SurveysCompleted {
            get {
                return ResourceManager.GetString("SurveysCompleted", resourceCulture);
            }
        }
        
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        public static string NewSurvey {
            get {
                return ResourceManager.GetString("NewSurvey", resourceCulture);
            }
        }
        
        public static string ThanksForCompleting {
            get {
                return ResourceManager.GetString("ThanksForCompleting", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        public static string SureArchive {
            get {
                return ResourceManager.GetString("SureArchive", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }
        
        public static string AddPrize {
            get {
                return ResourceManager.GetString("AddPrize", resourceCulture);
            }
        }
        
        public static string UploadPrizeImage {
            get {
                return ResourceManager.GetString("UploadPrizeImage", resourceCulture);
            }
        }
        
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        public static string SaveSurvey {
            get {
                return ResourceManager.GetString("SaveSurvey", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        public static string NoGroups {
            get {
                return ResourceManager.GetString("NoGroups", resourceCulture);
            }
        }
        
        public static string NotAMember {
            get {
                return ResourceManager.GetString("NotAMember", resourceCulture);
            }
        }
        
        public static string SaveFirst {
            get {
                return ResourceManager.GetString("SaveFirst", resourceCulture);
            }
        }
        
        public static string JoinGroups {
            get {
                return ResourceManager.GetString("JoinGroups", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string NoSurveys {
            get {
                return ResourceManager.GetString("NoSurveys", resourceCulture);
            }
        }
        
        public static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        public static string StartPrizeDraw {
            get {
                return ResourceManager.GetString("StartPrizeDraw", resourceCulture);
            }
        }
    }
}
